#!/bin/sh

# Start the untits
service ssh start
service nginx start
service mysql start
service php7.0-fpm start

if [ ! -f /firstrun.txt ]
then
    touch /firstrun.txt
    echo "Install PufferPanel"
    cd /etc/pufferpanel
    expect /etc/install
    rm /etc/install
    echo "DONE"
fi

# Start pufferd and pass the stdio to the container stdio
cd /srv/pufferd/
./pufferd --config /etc/pufferd/config.json